---
- hosts: localhost
  gather_facts: no

  tasks:
    - command: "{{ item }}"
      register: command_register
      ignore_errors: true
      no_log: true
      with_items:
        - date

    - debug: var=command_register
    - debug: msg="{{ command_register.results|map(attribute='stdout')|list }}"
