---

- name: update package 
  hosts: all
  become: true
  tasks:
    - name: update httpd package
      yum:
        name: httpd
        state: latest 
    - name: update list of packages
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - httpd
        - httpd-tools
    - name: update smart card support package group
      yum:
        name: '@Smart Card Support'
        state: latest 
    - name: update all installed packages
      yum:
        name: '*'
        state: latest
